# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(main_window)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.right = QtWidgets.QFrame(self.centralWidget)
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.right)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.right)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 473, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.right, 0, 2, 1, 1)
        self.left = QtWidgets.QFrame(self.centralWidget)
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.left)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.left)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.toolButton = QtWidgets.QToolButton(self.left)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.left)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 444, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.left, 0, 0, 1, 1)
        self.center = QtWidgets.QFrame(self.centralWidget)
        self.center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center.setObjectName("center")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.center)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.placeholder_1 = QtWidgets.QPushButton(self.center)
        self.placeholder_1.setObjectName("placeholder_1")
        self.verticalLayout.addWidget(self.placeholder_1)
        self.placeholder_2 = QtWidgets.QPushButton(self.center)
        self.placeholder_2.setObjectName("placeholder_2")
        self.verticalLayout.addWidget(self.placeholder_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.center, 0, 1, 1, 1)
        main_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuQuestion_Editor = QtWidgets.QMenu(self.menuBar)
        self.menuQuestion_Editor.setObjectName("menuQuestion_Editor")
        main_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(main_window)
        self.mainToolBar.setObjectName("mainToolBar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName("statusBar")
        main_window.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuQuestion_Editor.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.pushButton_2.setText(_translate("main_window", "Settings"))
        self.label.setText(_translate("main_window", "Choose working directory"))
        self.toolButton.setText(_translate("main_window", "..."))
        self.pushButton.setText(_translate("main_window", "Open Editor"))
        self.placeholder_1.setText(_translate("main_window", "placeholder 1"))
        self.placeholder_2.setText(_translate("main_window", "placeholder 2"))
        self.menuQuestion_Editor.setTitle(_translate("main_window", "File"))


