# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1366, 768)
        self.centralWidget = QtWidgets.QWidget(main_window)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.title_frame = QtWidgets.QFrame(self.centralWidget)
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.title_frame, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.day_frame = QtWidgets.QFrame(self.centralWidget)
        self.day_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.day_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.day_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.day_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.day_frame.setObjectName("day_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.day_frame)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headline_day = QtWidgets.QLabel(self.day_frame)
        self.headline_day.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.headline_day.setFont(font)
        self.headline_day.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_day.setObjectName("headline_day")
        self.verticalLayout_3.addWidget(self.headline_day)
        self.line = QtWidgets.QFrame(self.day_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_day = QtWidgets.QLabel(self.day_frame)
        self.label_day.setEnabled(False)
        self.label_day.setMinimumSize(QtCore.QSize(50, 0))
        self.label_day.setObjectName("label_day")
        self.horizontalLayout_4.addWidget(self.label_day)
        self.day_field = QtWidgets.QSpinBox(self.day_frame)
        self.day_field.setEnabled(False)
        self.day_field.setObjectName("day_field")
        self.horizontalLayout_4.addWidget(self.day_field)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_meta = QtWidgets.QLabel(self.day_frame)
        self.label_meta.setEnabled(False)
        self.label_meta.setMinimumSize(QtCore.QSize(50, 0))
        self.label_meta.setObjectName("label_meta")
        self.horizontalLayout_3.addWidget(self.label_meta)
        self.meta_field = QtWidgets.QPlainTextEdit(self.day_frame)
        self.meta_field.setEnabled(False)
        self.meta_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.meta_field.setObjectName("meta_field")
        self.horizontalLayout_3.addWidget(self.meta_field)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_blocks = QtWidgets.QLabel(self.day_frame)
        self.label_blocks.setEnabled(False)
        self.label_blocks.setMinimumSize(QtCore.QSize(50, 0))
        self.label_blocks.setObjectName("label_blocks")
        self.horizontalLayout_6.addWidget(self.label_blocks)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.block_list = QtWidgets.QListWidget(self.day_frame)
        self.block_list.setEnabled(False)
        self.block_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.block_list.setObjectName("block_list")
        self.verticalLayout_2.addWidget(self.block_list)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.new_block_button = QtWidgets.QPushButton(self.day_frame)
        self.new_block_button.setEnabled(False)
        self.new_block_button.setObjectName("new_block_button")
        self.horizontalLayout_5.addWidget(self.new_block_button)
        self.edit_block_button = QtWidgets.QPushButton(self.day_frame)
        self.edit_block_button.setEnabled(False)
        self.edit_block_button.setObjectName("edit_block_button")
        self.horizontalLayout_5.addWidget(self.edit_block_button)
        self.delete_block_button = QtWidgets.QPushButton(self.day_frame)
        self.delete_block_button.setEnabled(False)
        self.delete_block_button.setObjectName("delete_block_button")
        self.horizontalLayout_5.addWidget(self.delete_block_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.day_frame, 0, 2, 1, 1)
        self.days_frame = QtWidgets.QFrame(self.centralWidget)
        self.days_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.days_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.days_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.days_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.days_frame.setObjectName("days_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.days_frame)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.headline_days = QtWidgets.QLabel(self.days_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.headline_days.setFont(font)
        self.headline_days.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_days.setObjectName("headline_days")
        self.gridLayout_5.addWidget(self.headline_days, 0, 0, 1, 1)
        self.day_list = QtWidgets.QListWidget(self.days_frame)
        self.day_list.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.day_list.setObjectName("day_list")
        self.gridLayout_5.addWidget(self.day_list, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_day_button = QtWidgets.QPushButton(self.days_frame)
        self.new_day_button.setObjectName("new_day_button")
        self.horizontalLayout_2.addWidget(self.new_day_button)
        self.delete_day_button = QtWidgets.QPushButton(self.days_frame)
        self.delete_day_button.setObjectName("delete_day_button")
        self.horizontalLayout_2.addWidget(self.delete_day_button)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.days_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.days_frame, 0, 1, 1, 1)
        self.settings_frame = QtWidgets.QFrame(self.centralWidget)
        self.settings_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.settings_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.settings_frame)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.directory_display = QtWidgets.QLineEdit(self.settings_frame)
        self.directory_display.setReadOnly(True)
        self.directory_display.setObjectName("directory_display")
        self.horizontalLayout.addWidget(self.directory_display)
        self.directory_tool = QtWidgets.QToolButton(self.settings_frame)
        self.directory_tool.setObjectName("directory_tool")
        self.horizontalLayout.addWidget(self.directory_tool)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.placeholder_1 = QtWidgets.QPushButton(self.settings_frame)
        self.placeholder_1.setObjectName("placeholder_1")
        self.verticalLayout.addWidget(self.placeholder_1)
        self.placeholder_2 = QtWidgets.QPushButton(self.settings_frame)
        self.placeholder_2.setObjectName("placeholder_2")
        self.verticalLayout.addWidget(self.placeholder_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.settings_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.settings_frame, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        main_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1366, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuQuestion_Editor = QtWidgets.QMenu(self.menuBar)
        self.menuQuestion_Editor.setObjectName("menuQuestion_Editor")
        main_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(main_window)
        self.mainToolBar.setObjectName("mainToolBar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName("statusBar")
        main_window.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuQuestion_Editor.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.label_2.setText(_translate("main_window", "diary-survey-bot | survey-editor"))
        self.headline_day.setText(_translate("main_window", "Day"))
        self.label_day.setText(_translate("main_window", "Day"))
        self.label_meta.setText(_translate("main_window", "Meta"))
        self.meta_field.setPlaceholderText(_translate("main_window", "Fill in some meta information."))
        self.label_blocks.setText(_translate("main_window", "Blocks"))
        self.new_block_button.setText(_translate("main_window", "new"))
        self.edit_block_button.setText(_translate("main_window", "edit"))
        self.delete_block_button.setText(_translate("main_window", "delete"))
        self.headline_days.setText(_translate("main_window", "Days"))
        self.new_day_button.setText(_translate("main_window", "new"))
        self.delete_day_button.setText(_translate("main_window", "delete"))
        self.directory_display.setPlaceholderText(_translate("main_window", "Choose working directory."))
        self.directory_tool.setText(_translate("main_window", "..."))
        self.placeholder_1.setText(_translate("main_window", "placeholder 1"))
        self.placeholder_2.setText(_translate("main_window", "placeholder 2"))
        self.pushButton_2.setText(_translate("main_window", "Settings"))
        self.menuQuestion_Editor.setTitle(_translate("main_window", "File"))


