# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_question(object):
    def setupUi(self, question):
        question.setObjectName("question")
        question.setEnabled(False)
        question.resize(1100, 600)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        question.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(question)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_frame = QtWidgets.QFrame(question)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.data_frame.setFont(font)
        self.data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_frame.setObjectName("data_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.data_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.variable_field = QtWidgets.QLineEdit(self.data_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.variable_field.setFont(font)
        self.variable_field.setText("")
        self.variable_field.setObjectName("variable_field")
        self.gridLayout.addWidget(self.variable_field, 2, 2, 1, 1)
        self.meta_field = QtWidgets.QPlainTextEdit(self.data_frame)
        self.meta_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.meta_field.setFont(font)
        self.meta_field.setObjectName("meta_field")
        self.gridLayout.addWidget(self.meta_field, 1, 2, 1, 1)
        self.text_label = QtWidgets.QLabel(self.data_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.gridLayout.addWidget(self.text_label, 0, 0, 1, 2)
        self.meta_label = QtWidgets.QLabel(self.data_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.meta_label.setFont(font)
        self.meta_label.setObjectName("meta_label")
        self.gridLayout.addWidget(self.meta_label, 1, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.data_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 3, 2, 1, 1)
        self.variable_label = QtWidgets.QLabel(self.data_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.variable_label.setFont(font)
        self.variable_label.setObjectName("variable_label")
        self.gridLayout.addWidget(self.variable_label, 2, 0, 1, 1)
        self.text_field = QtWidgets.QPlainTextEdit(self.data_frame)
        self.text_field.setMinimumSize(QtCore.QSize(250, 100))
        self.text_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.text_field.setFont(font)
        self.text_field.setObjectName("text_field")
        self.gridLayout.addWidget(self.text_field, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.data_frame, 1, 0, 1, 1)
        self.title_frame = QtWidgets.QFrame(question)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.title_frame.setFont(font)
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.headline = QtWidgets.QLabel(self.title_frame)
        self.headline.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.headline.setFont(font)
        self.headline.setAlignment(QtCore.Qt.AlignCenter)
        self.headline.setObjectName("headline")
        self.gridLayout_5.addWidget(self.headline, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_6 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_9.addWidget(self.line_6)
        self.lang_info = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.lang_info.setFont(font)
        self.lang_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lang_info.setObjectName("lang_info")
        self.horizontalLayout_9.addWidget(self.lang_info)
        self.line_5 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_9.addWidget(self.line_5)
        self.day_info = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.day_info.setFont(font)
        self.day_info.setAlignment(QtCore.Qt.AlignCenter)
        self.day_info.setObjectName("day_info")
        self.horizontalLayout_9.addWidget(self.day_info)
        self.line_7 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_9.addWidget(self.line_7)
        self.block_info = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.block_info.setFont(font)
        self.block_info.setAlignment(QtCore.Qt.AlignCenter)
        self.block_info.setObjectName("block_info")
        self.horizontalLayout_9.addWidget(self.block_info)
        self.line_8 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_9.addWidget(self.line_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.line_3 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_10.addWidget(self.line_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.title_frame)
        self.lineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.title_frame)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.title_frame)
        self.comboBox_2.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_11.addWidget(self.comboBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.title_frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.title_frame, 0, 0, 1, 1)
        self.Commands = QtWidgets.QFrame(question)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.Commands.setFont(font)
        self.Commands.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Commands.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Commands.setObjectName("Commands")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Commands)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_9 = QtWidgets.QFrame(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.line_9.setFont(font)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headline_condition = QtWidgets.QLabel(self.Commands)
        self.headline_condition.setMinimumSize(QtCore.QSize(0, 18))
        self.headline_condition.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.headline_condition.setFont(font)
        self.headline_condition.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_condition.setObjectName("headline_condition")
        self.verticalLayout_3.addWidget(self.headline_condition)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.headline_condition_key = QtWidgets.QLabel(self.Commands)
        self.headline_condition_key.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_condition_key.setFont(font)
        self.headline_condition_key.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_condition_key.setObjectName("headline_condition_key")
        self.verticalLayout.addWidget(self.headline_condition_key)
        self.keyword_field = QtWidgets.QLineEdit(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.keyword_field.setFont(font)
        self.keyword_field.setObjectName("keyword_field")
        self.verticalLayout.addWidget(self.keyword_field)
        self.headline_condition_choice = QtWidgets.QLabel(self.Commands)
        self.headline_condition_choice.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_condition_choice.setFont(font)
        self.headline_condition_choice.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_condition_choice.setObjectName("headline_condition_choice")
        self.verticalLayout.addWidget(self.headline_condition_choice)
        self.condition_choice_list = QtWidgets.QListWidget(self.Commands)
        self.condition_choice_list.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_choice_list.setFont(font)
        self.condition_choice_list.setObjectName("condition_choice_list")
        self.verticalLayout.addWidget(self.condition_choice_list)
        self.condition_add_button = QtWidgets.QPushButton(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_add_button.setFont(font)
        self.condition_add_button.setObjectName("condition_add_button")
        self.verticalLayout.addWidget(self.condition_add_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headline_conditions = QtWidgets.QLabel(self.Commands)
        self.headline_conditions.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_conditions.setFont(font)
        self.headline_conditions.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_conditions.setObjectName("headline_conditions")
        self.verticalLayout_2.addWidget(self.headline_conditions)
        self.condition_list = QtWidgets.QTableWidget(self.Commands)
        self.condition_list.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_list.setFont(font)
        self.condition_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.condition_list.setAlternatingRowColors(True)
        self.condition_list.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.condition_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.condition_list.setObjectName("condition_list")
        self.condition_list.setColumnCount(2)
        self.condition_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.condition_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.condition_list.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.condition_list)
        self.condition_delete_button = QtWidgets.QPushButton(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_delete_button.setFont(font)
        self.condition_delete_button.setObjectName("condition_delete_button")
        self.verticalLayout_2.addWidget(self.condition_delete_button)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.headline_condition_rq = QtWidgets.QLabel(self.Commands)
        self.headline_condition_rq.setMinimumSize(QtCore.QSize(0, 18))
        self.headline_condition_rq.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.headline_condition_rq.setFont(font)
        self.headline_condition_rq.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_condition_rq.setObjectName("headline_condition_rq")
        self.verticalLayout_7.addWidget(self.headline_condition_rq)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.headline_all_conditions = QtWidgets.QLabel(self.Commands)
        self.headline_all_conditions.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_all_conditions.setFont(font)
        self.headline_all_conditions.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_all_conditions.setObjectName("headline_all_conditions")
        self.verticalLayout_5.addWidget(self.headline_all_conditions)
        self.all_conditions_list = QtWidgets.QTableWidget(self.Commands)
        self.all_conditions_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.all_conditions_list.setFont(font)
        self.all_conditions_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.all_conditions_list.setAlternatingRowColors(True)
        self.all_conditions_list.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.all_conditions_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.all_conditions_list.setObjectName("all_conditions_list")
        self.all_conditions_list.setColumnCount(2)
        self.all_conditions_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.all_conditions_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.all_conditions_list.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.all_conditions_list)
        self.condition_rq_add_button = QtWidgets.QPushButton(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_rq_add_button.setFont(font)
        self.condition_rq_add_button.setObjectName("condition_rq_add_button")
        self.verticalLayout_5.addWidget(self.condition_rq_add_button)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.headline_rq_conditions = QtWidgets.QLabel(self.Commands)
        self.headline_rq_conditions.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_rq_conditions.setFont(font)
        self.headline_rq_conditions.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_rq_conditions.setObjectName("headline_rq_conditions")
        self.verticalLayout_6.addWidget(self.headline_rq_conditions)
        self.rq_conditions_list = QtWidgets.QTableWidget(self.Commands)
        self.rq_conditions_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.rq_conditions_list.setFont(font)
        self.rq_conditions_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.rq_conditions_list.setAlternatingRowColors(True)
        self.rq_conditions_list.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.rq_conditions_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.rq_conditions_list.setObjectName("rq_conditions_list")
        self.rq_conditions_list.setColumnCount(2)
        self.rq_conditions_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rq_conditions_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rq_conditions_list.setHorizontalHeaderItem(1, item)
        self.verticalLayout_6.addWidget(self.rq_conditions_list)
        self.condition_rq_delete_button = QtWidgets.QPushButton(self.Commands)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.condition_rq_delete_button.setFont(font)
        self.condition_rq_delete_button.setObjectName("condition_rq_delete_button")
        self.verticalLayout_6.addWidget(self.condition_rq_delete_button)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Commands, 0, 2, 2, 1)
        self.config_frame = QtWidgets.QFrame(question)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.config_frame.setFont(font)
        self.config_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.config_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.config_frame.setObjectName("config_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headline_choices = QtWidgets.QLabel(self.config_frame)
        self.headline_choices.setMinimumSize(QtCore.QSize(0, 18))
        self.headline_choices.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.headline_choices.setFont(font)
        self.headline_choices.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_choices.setObjectName("headline_choices")
        self.verticalLayout_4.addWidget(self.headline_choices)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.headline_templates = QtWidgets.QLabel(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.headline_templates.setFont(font)
        self.headline_templates.setObjectName("headline_templates")
        self.horizontalLayout.addWidget(self.headline_templates)
        self.comboBox = QtWidgets.QComboBox(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.comboBox.setFont(font)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.choice_field = QtWidgets.QPlainTextEdit(self.config_frame)
        self.choice_field.setMaximumSize(QtCore.QSize(16777215, 190))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.choice_field.setFont(font)
        self.choice_field.setObjectName("choice_field")
        self.horizontalLayout_2.addWidget(self.choice_field)
        self.choice_list = QtWidgets.QListWidget(self.config_frame)
        self.choice_list.setMaximumSize(QtCore.QSize(16777215, 190))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.choice_list.setFont(font)
        self.choice_list.setAcceptDrops(False)
        self.choice_list.setDragEnabled(True)
        self.choice_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.choice_list.setObjectName("choice_list")
        self.horizontalLayout_2.addWidget(self.choice_list)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choice_add_button = QtWidgets.QPushButton(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.choice_add_button.setFont(font)
        self.choice_add_button.setObjectName("choice_add_button")
        self.horizontalLayout_3.addWidget(self.choice_add_button)
        self.choice_delete_button = QtWidgets.QPushButton(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.choice_delete_button.setFont(font)
        self.choice_delete_button.setObjectName("choice_delete_button")
        self.horizontalLayout_3.addWidget(self.choice_delete_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.config_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.headline_commands = QtWidgets.QLabel(self.config_frame)
        self.headline_commands.setMinimumSize(QtCore.QSize(0, 18))
        self.headline_commands.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.headline_commands.setFont(font)
        self.headline_commands.setAlignment(QtCore.Qt.AlignCenter)
        self.headline_commands.setObjectName("headline_commands")
        self.verticalLayout_8.addWidget(self.headline_commands)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.commands_field = QtWidgets.QLineEdit(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.commands_field.setFont(font)
        self.commands_field.setReadOnly(True)
        self.commands_field.setPlaceholderText("")
        self.commands_field.setObjectName("commands_field")
        self.horizontalLayout_6.addWidget(self.commands_field)
        self.data_name_field = QtWidgets.QLineEdit(self.config_frame)
        self.data_name_field.setObjectName("data_name_field")
        self.horizontalLayout_6.addWidget(self.data_name_field)
        self.data_box = QtWidgets.QComboBox(self.config_frame)
        self.data_box.setObjectName("data_box")
        self.data_box.addItem("")
        self.data_box.addItem("")
        self.horizontalLayout_6.addWidget(self.data_box)
        self.command_data_add_button = QtWidgets.QPushButton(self.config_frame)
        self.command_data_add_button.setMaximumSize(QtCore.QSize(55, 16777215))
        self.command_data_add_button.setObjectName("command_data_add_button")
        self.horizontalLayout_6.addWidget(self.command_data_add_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.commands_combobox = QtWidgets.QComboBox(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.commands_combobox.setFont(font)
        self.commands_combobox.setObjectName("commands_combobox")
        self.horizontalLayout_8.addWidget(self.commands_combobox)
        self.command_add_button = QtWidgets.QPushButton(self.config_frame)
        self.command_add_button.setMaximumSize(QtCore.QSize(55, 16777215))
        self.command_add_button.setObjectName("command_add_button")
        self.horizontalLayout_8.addWidget(self.command_add_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.commands_list = QtWidgets.QListWidget(self.config_frame)
        self.commands_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.commands_list.setFont(font)
        self.commands_list.setObjectName("commands_list")
        self.verticalLayout_8.addWidget(self.commands_list)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.commands_delete_button = QtWidgets.QPushButton(self.config_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.commands_delete_button.setFont(font)
        self.commands_delete_button.setObjectName("commands_delete_button")
        self.horizontalLayout_7.addWidget(self.commands_delete_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.config_frame, 0, 1, 2, 1)
        self.text_label.setBuddy(self.text_field)
        self.meta_label.setBuddy(self.meta_field)
        self.variable_label.setBuddy(self.variable_field)

        self.retranslateUi(question)
        QtCore.QMetaObject.connectSlotsByName(question)
        question.setTabOrder(self.lineEdit, self.pushButton)
        question.setTabOrder(self.pushButton, self.comboBox_2)
        question.setTabOrder(self.comboBox_2, self.pushButton_2)
        question.setTabOrder(self.pushButton_2, self.text_field)
        question.setTabOrder(self.text_field, self.meta_field)
        question.setTabOrder(self.meta_field, self.variable_field)
        question.setTabOrder(self.variable_field, self.save_button)
        question.setTabOrder(self.save_button, self.comboBox)
        question.setTabOrder(self.comboBox, self.choice_field)
        question.setTabOrder(self.choice_field, self.choice_list)
        question.setTabOrder(self.choice_list, self.choice_add_button)
        question.setTabOrder(self.choice_add_button, self.choice_delete_button)
        question.setTabOrder(self.choice_delete_button, self.keyword_field)
        question.setTabOrder(self.keyword_field, self.condition_choice_list)
        question.setTabOrder(self.condition_choice_list, self.condition_add_button)
        question.setTabOrder(self.condition_add_button, self.condition_list)
        question.setTabOrder(self.condition_list, self.condition_delete_button)
        question.setTabOrder(self.condition_delete_button, self.all_conditions_list)
        question.setTabOrder(self.all_conditions_list, self.condition_rq_add_button)
        question.setTabOrder(self.condition_rq_add_button, self.rq_conditions_list)
        question.setTabOrder(self.rq_conditions_list, self.condition_rq_delete_button)
        question.setTabOrder(self.condition_rq_delete_button, self.commands_field)
        question.setTabOrder(self.commands_field, self.commands_list)
        question.setTabOrder(self.commands_list, self.commands_delete_button)

    def retranslateUi(self, question):
        _translate = QtCore.QCoreApplication.translate
        question.setWindowTitle(_translate("question", "Form"))
        self.variable_field.setPlaceholderText(_translate("question", "Pick a variable name. (not mandatory)"))
        self.meta_field.setPlaceholderText(_translate("question", "Fill in any notes or meta information."))
        self.text_label.setText(_translate("question", "Question "))
        self.meta_label.setText(_translate("question", "Meta "))
        self.save_button.setText(_translate("question", "save"))
        self.variable_label.setText(_translate("question", "Variable"))
        self.text_field.setPlaceholderText(_translate("question", "Fill in the question to be asked."))
        self.headline.setText(_translate("question", "Question X"))
        self.lang_info.setText(_translate("question", "Language: X"))
        self.day_info.setText(_translate("question", "Day: X"))
        self.block_info.setText(_translate("question", "Block: X"))
        self.label.setText(_translate("question", "Store template"))
        self.lineEdit.setPlaceholderText(_translate("question", "Pick a name."))
        self.pushButton.setText(_translate("question", "store"))
        self.label_2.setText(_translate("question", "Load template"))
        self.pushButton_2.setText(_translate("question", "load"))
        self.headline_condition.setText(_translate("question", "Condition"))
        self.headline_condition_key.setText(_translate("question", "Keyword"))
        self.keyword_field.setPlaceholderText(_translate("question", "Pick a keyword for the condition."))
        self.headline_condition_choice.setText(_translate("question", "Choice"))
        self.condition_add_button.setText(_translate("question", "add/edit"))
        self.headline_conditions.setText(_translate("question", "Conditions"))
        item = self.condition_list.horizontalHeaderItem(0)
        item.setText(_translate("question", "Choice"))
        item = self.condition_list.horizontalHeaderItem(1)
        item.setText(_translate("question", "Key"))
        self.condition_delete_button.setText(_translate("question", "delete"))
        self.headline_condition_rq.setText(_translate("question", "Condition Required"))
        self.headline_all_conditions.setText(_translate("question", "All Conditions"))
        item = self.all_conditions_list.horizontalHeaderItem(0)
        item.setText(_translate("question", "Choice"))
        item = self.all_conditions_list.horizontalHeaderItem(1)
        item.setText(_translate("question", "Key"))
        self.condition_rq_add_button.setText(_translate("question", "add"))
        self.headline_rq_conditions.setText(_translate("question", "Required Conditions"))
        item = self.rq_conditions_list.horizontalHeaderItem(0)
        item.setText(_translate("question", "Choice"))
        item = self.rq_conditions_list.horizontalHeaderItem(1)
        item.setText(_translate("question", "Key"))
        self.condition_rq_delete_button.setText(_translate("question", "delete"))
        self.headline_choices.setText(_translate("question", "Choices"))
        self.headline_templates.setText(_translate("question", "Templates/Custom"))
        self.choice_field.setPlaceholderText(_translate("question", "Fill in a possible answer."))
        self.choice_add_button.setText(_translate("question", "add/edit"))
        self.choice_delete_button.setText(_translate("question", "delete"))
        self.headline_commands.setText(_translate("question", "Commands"))
        self.commands_field.setText(_translate("question", "DATA"))
        self.data_name_field.setPlaceholderText(_translate("question", "DATA_NAME"))
        self.data_box.setItemText(0, _translate("question", "ADD"))
        self.data_box.setItemText(1, _translate("question", "CLR"))
        self.command_data_add_button.setText(_translate("question", "add"))
        self.command_add_button.setText(_translate("question", "add"))
        self.commands_delete_button.setText(_translate("question", "delete"))


