# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_question(object):
    def setupUi(self, question):
        question.setObjectName("question")
        question.resize(800, 600)
        self.gridLayout_5 = QtWidgets.QGridLayout(question)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.control_frame = QtWidgets.QFrame(question)
        self.control_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.control_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_button = QtWidgets.QPushButton(self.control_frame)
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout.addWidget(self.prev_button)
        self.save_button = QtWidgets.QPushButton(self.control_frame)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.next_button = QtWidgets.QPushButton(self.control_frame)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.control_frame, 2, 1, 1, 1)
        self.title_frame = QtWidgets.QFrame(question)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.headline = QtWidgets.QLabel(self.title_frame)
        self.headline.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.headline.setFont(font)
        self.headline.setAlignment(QtCore.Qt.AlignCenter)
        self.headline.setObjectName("headline")
        self.gridLayout_4.addWidget(self.headline, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.title_frame, 0, 0, 1, 1)
        self.config_frame = QtWidgets.QFrame(question)
        self.config_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.config_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.config_frame.setObjectName("config_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.config_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.config_frame, 0, 1, 2, 1)
        self.data_frame = QtWidgets.QFrame(question)
        self.data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_frame.setObjectName("data_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.data_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.meta_field = QtWidgets.QTextEdit(self.data_frame)
        self.meta_field.setObjectName("meta_field")
        self.gridLayout.addWidget(self.meta_field, 1, 2, 1, 1)
        self.variable_field = QtWidgets.QLineEdit(self.data_frame)
        self.variable_field.setObjectName("variable_field")
        self.gridLayout.addWidget(self.variable_field, 2, 2, 1, 1)
        self.meta_label = QtWidgets.QLabel(self.data_frame)
        self.meta_label.setObjectName("meta_label")
        self.gridLayout.addWidget(self.meta_label, 1, 0, 1, 1)
        self.variable_label = QtWidgets.QLabel(self.data_frame)
        self.variable_label.setObjectName("variable_label")
        self.gridLayout.addWidget(self.variable_label, 2, 0, 1, 1)
        self.text_label = QtWidgets.QLabel(self.data_frame)
        self.text_label.setObjectName("text_label")
        self.gridLayout.addWidget(self.text_label, 0, 0, 1, 2)
        self.text_field = QtWidgets.QTextEdit(self.data_frame)
        self.text_field.setObjectName("text_field")
        self.gridLayout.addWidget(self.text_field, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.data_frame, 1, 0, 2, 1)
        self.meta_label.setBuddy(self.meta_field)
        self.variable_label.setBuddy(self.variable_field)
        self.text_label.setBuddy(self.text_field)

        self.retranslateUi(question)
        QtCore.QMetaObject.connectSlotsByName(question)

    def retranslateUi(self, question):
        _translate = QtCore.QCoreApplication.translate
        question.setWindowTitle(_translate("question", "Form"))
        self.prev_button.setText(_translate("question", "prev"))
        self.save_button.setText(_translate("question", "save"))
        self.next_button.setText(_translate("question", "next"))
        self.headline.setText(_translate("question", "Question X"))
        self.meta_label.setText(_translate("question", "Meta Info"))
        self.variable_label.setText(_translate("question", "Variable"))
        self.text_label.setText(_translate("question", "Question Text"))


